Fix: BadRequest: NetworkAcls is required for this resouce.
Fixes the error:

ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:

Deployment Error Details:
BadRequest: NetworkAcls is required for this resouce.